# Generated by go2rpm 1.14.0
%bcond check 1
%bcond bootstrap 0

%global debug_package %{nil}
%if %{with bootstrap}
%global __requires_exclude %{?__requires_exclude:%{__requires_exclude}|}^golang\\(.*\\)$
%endif

# https://github.com/jwalton/gchalk
%global goipath         github.com/jwalton/gchalk
Version:                1.3.0

%gometa -L -f

%global common_description %{expand:
Terminal string styling for go done right, with full and painless Windows 10
support.}

%global golicenses      LICENSE LICENSE-chalk pkg/ansistyles/LICENSE\\\
                        pkg/ansistyles/LICENSE-ansi-styles
%global godocs          README.md architecture.md pkg/ansistyles/README.md

Name:           golang-github-jwalton-gchalk
Release:        %autorelease
Summary:        Terminal string styling for go done right, with full and painless Windows 10 support

License:        MIT
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
%goprep -A
%autopatch -p1

%if %{without bootstrap}
%generate_buildrequires
%go_generate_buildrequires
%endif

%install
%gopkginstall

%if %{without bootstrap}
%if %{with check}
%check
%gocheck
%endif
%endif

%gopkgfiles

%changelog
%autochangelog
