# Generated by go2rpm 1.14.0
%bcond check 1
%bcond bootstrap 0

%if %{with bootstrap}
%global debug_package %{nil}
%endif

%if %{with bootstrap}
%global __requires_exclude %{?__requires_exclude:%{__requires_exclude}|}^golang\\(.*\\)$
%endif

# https://github.com/noborus/ov
%global goipath         github.com/noborus/ov
Version:                0.35.0

%gometa -L -f

%global common_description %{expand:
Feature-rich terminal-based text viewer. It is a so-called terminal pager.}

%global golicenses      LICENSE
%global godocs          docs examples CODE_OF_CONDUCT.md README.md

Name:           ov
Release:        %autorelease
Summary:        Feature-rich terminal-based text viewer

License:        MIT
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
%goprep -A
%autopatch -p1

%if %{without bootstrap}
%generate_buildrequires
%go_generate_buildrequires
%endif

%if %{without bootstrap}
%build
%gobuild -o %{gobuilddir}/bin/ov %{goipath}
%endif

%install
%gopkginstall
%if %{without bootstrap}
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/
%endif

%if %{without bootstrap}
%if %{with check}
%check
%gocheck
%endif
%endif

%if %{without bootstrap}
%files
%license LICENSE
%doc docs examples CODE_OF_CONDUCT.md README.md
%{_bindir}/ov
%endif

%gopkgfiles

%changelog
%autochangelog
